### ISSUE TITLE
About Camera ISP and drivers.

### ISSUE THREAD

**Issue by alifilhan0** [Maccraft123/Cadmium#11]
I think the ISP drivers are not in the mainline kernel right? But they were in the 4.19 chrome os kernel. Is there any ways to get cameras working? IS work going on with the ISP drivers yet? Actually I am working to get mainlined bits of linux kernel running on a MT6735 device. 

Looking forward for your kind reply, thanks.

**Comment by Maccraft123** [comment]
Hello, from what I see on mailing list, there have been attempts at upstreaming mt8183 camera driver, but it didn't make it into mainline.
My guess is that mediatek engineers decided to wait with sending camera patches until they get more useful hardware running(display just barely got into mainline and resuming from suspend is broken)

**Comment by alifilhan0** [comment]
They are just more busy adding new SoC entries than trying to upstream the drivers first. This is sad. If they do it the opposite and try to upstream the required drivers quicker, it would be much better.
