### ISSUE TITLE
Install on SD Card (install-to-here) results in root partition full

### ISSUE THREAD

**Issue by cvmiller** [Maccraft123/Cadmium#110]
I am still learning Cadmium, and not ready to blow away ChromeOS. So I have been using the 'install-to-here' script to install on the SD Card.

This works, but the partition is only 2GB, and fills up (when installing phosh UI). So, I took out the SD card, used `gparted` in another machine to "grow" the size of the root partition (it is a 32GB SD card), which looks like it worked.

However, when I try to boot at the white screen with ctrl-U, I get a beep, and the SD card will no longer boot.

How does one grow the root partition in Cadmium? TIA

**Comment by cvmiller** [comment]
I was unable to find a successful way to grow the root partition on the installer media (SD card or USB stick).

I eventually used 2 SD cards, one with the installer, and one in a USB adapter. I did the following to install on the second SD card:

1. copy install-to-emmc script to install-sd
2. Edit install-sd adding the following below the EMMC line, thus hard coding the variable to /dev/sda
`EMMC=/dev/sda`
3. Run `install-sd` and I selected UI as 'none'.
4. Rebooted with just the second SD (now freshly installed) plugged into the Chromebook
5. Noted that the root partition is now ~30GB
6. Used `apt` to install `lxde`, which pulls in `lightdm` Chromebook works quite well

At some point, I'll be ready to wipe Chrome from this machine (an Asus C201PA), but for now, I am happy running it off an SD card.

**Comment by Maccraft123** [comment]
Yea, i'll add resizing root partition in future

**Comment by cvmiller** [comment]
I look forward to it.

**Comment by Wooty-B** [comment]
> I was unable to find a successful way to grow the root partition on the installer media (SD card or USB stick).
> 
> I eventually used 2 SD cards, one with the installer, and one in a USB adapter. I did the following to install on the second SD card:
> 
>     1. copy install-to-emmc script to install-sd
> 
>     2. Edit install-sd adding the following below the EMMC line, thus hard coding the variable to /dev/sda
>        `EMMC=/dev/sda`
> 
>     3. Run `install-sd` and I selected UI as 'none'.
> 
>     4. Rebooted with just the second SD (now freshly installed) plugged into the Chromebook
> 
>     5. Noted that the root partition is now ~30GB
> 
>     6. Used `apt` to install `lxde`, which pulls in `lightdm` Chromebook works quite well
> 
> 
> At some point, I'll be ready to wipe Chrome from this machine (an Asus C201PA), but for now, I am happy running it off an SD card.

In case anyone else is looking for this, the exact line you need to change is a few lines down at the beginning of the script:

#a fancy hack
MMCDEV=/dev/sdX  (For USB)
MMCDEV=/dev/mmcblkX (For uSD/eMMC)

My uSD install also suffered from the inability to resize using f2fs tools even from another system, hope this gets implemented soon as that is the only real issue I have come across using/installing Cadmium.
