### ISSUE TITLE
Feature Request: Add more kernel modules (USB Ethernet Dongle, FUSE)

### ISSUE THREAD

**Issue by cvmiller** [Maccraft123/Cadmium#112]
I am running Speedy (C201PA) with release 0.3.0 and I have found a couple of kmods that would be nice to have:

* FUSE - allows user space file mounting, such as `sshfs`
* USB Ethernet Dongle support (I have a D-Link DUB-1312), as well as a StarTech (Moschip Semi))

**Comment by cvmiller** [comment]
More info on the Ethernet Dongle

`dmesg` reports:

 ax88179_178a 1-1:1.0 eth0: register 'ax88179_178a' at usb-0000:00:04.1-1, D-Link DUB-1312 USB 3.0 to Gigabit Ethernet Adapter, 9c:d6:43:ae:19:15

`lsmod` reports:

```
Module                  Size  Used by
ax88179_178a           36864  0
usbnet                 53248  1 ax88179_178a
mii                    16384  2 usbnet,ax88179_178a
```

**Comment by Wooty-B** [comment]
Possibly iso9660 CD ISO images as well. I am unable to mount .iso images due to lack of kernel module so my workaround is to use "7z" to extract contents of ISO files.
