### ISSUE TITLE
Issues Booting on Lenovo Duet

### ISSUE THREAD

**Issue by EtherealSerge** [Maccraft123/Cadmium#12]
After a few fits and starts, was finally able to select boot from usb in Developer Mode startup screen, but when I do it eventually boots to a login screen. I'm not sure what the login should be or if I'm just missing a step. I wrote the img with the ChromeOs backup utility so that should be good.

Any help would be appreciated!

**Comment by Maccraft123** [comment]
You just login as root and install to emmc using ```./install-to-emmc``` command. It should guide you through.
It WILL nuke your chromeos installation
If you need any help join discord or irc

**Comment by EtherealSerge** [comment]
Awesome, thanks so much!
