### ISSUE TITLE
Sound not working on Duet

### ISSUE THREAD

**Issue by silverwizard** [Maccraft123/Cadmium#120]
I loaded the new release on a clean Ideapad Duet.

I can only see the Dummy audia device in the list, I see this in dmesg. Sound was working on ChromeOS.

```[    0.501207] mt8183_mt6358_ts3a227 mt8183-sound: mt8183_mt6358_ts3a227_max98357_dev_probe Can't find pin state wov -19```

**Comment by Maccraft123** [comment]
Fixed in master branch by: https://github.com/Maccraft123/Cadmium/commit/477282cc8e8789f77922526942e09c68ad03e72f

**Comment by silverwizard** [comment]
That fixed it
