### ISSUE TITLE
Lenovo IdeaPad 3 Black Screen FENNEL14 (kukui board)

### ISSUE THREAD

**Issue by BenjaminWegener** [Maccraft123/Cadmium#122]
I can boot from USB the cadmium-debian 64 ISO, but just showing me black screen.
I now build the krane513 tree, maybe thats gonna work. Will keep you posted.

**Comment by Maccraft123** [comment]
Can you give *exact* model number of your device?

**Comment by BenjaminWegener** [comment]
you mean FENNEL14-DWCY?

**Comment by Maccraft123** [comment]
DTB file for it isn't added to Cadmium, as it's unsupported.
If you can build cadmium try adding a section with dtb files that contain `fennel14` in their name.
If you don't know how, feel free to ask

**Comment by BenjaminWegener** [comment]
sure, would be nice to get some help. so i git clone the master, what do i have to write in the config? baseboard should be kukui, as its 8183 too. and whats a dtb file?

**Comment by chinh4thepro** [comment]
https://github.com/BenjaminWegener/Cadmium/pull/1
added dtb files for the fennel14 board

**Comment by BenjaminWegener** [comment]
Testing is asap

**Comment by BenjaminWegener** [comment]
staying dark on boot, cant verify if pendrive does something, its one without led
only image i can boot is kukui over at imagebuilder with 5.13 kernel

**Comment by BenjaminWegener** [comment]
started to try all possible configurations, hopefully some will show me something other than a blank screen.
-> will track the progress here

**Comment by BenjaminWegener** [comment]
https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/issues/2#issuecomment-1106693449
