### ISSUE TITLE
build fails with 'can't find file to patch at input line 69'

### ISSUE THREAD

**Issue by BenjaminWegener** [Maccraft123/Cadmium#124]
Building from source these days (ubuntu 20.04 x64 AND ubuntu 22.04 arm64) fails unexpectedly with:

Applying /home/linux/Documents/Cadmium/kernel/patches/common.android-enable-building-ashmem-and-binder-as-modules.patch
patching file drivers/android/Kconfig
patching file drivers/android/Makefile
patching file drivers/android/binder_alloc.c
can't find file to patch at input line 69
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:

|Index: b/drivers/staging/android/Kconfig
|===================================================================
|--- a/drivers/staging/android/Kconfig
|+++ b/drivers/staging/android/Kconfig
File to patch:

**Comment by chinh4thepro** [comment]
I'm having the same problem and when I try to skip I get, 

Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: b/drivers/staging/android/Kconfig
|===================================================================
|--- a/drivers/staging/android/Kconfig
|+++ b/drivers/staging/android/Kconfig
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 82
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: b/drivers/staging/android/Makefile
|===================================================================
|--- a/drivers/staging/android/Makefile
|+++ b/drivers/staging/android/Makefile
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 93
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: b/drivers/staging/android/ashmem.c
|===================================================================
|--- a/drivers/staging/android/ashmem.c
|+++ b/drivers/staging/android/ashmem.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored

**Comment by danijell2** [comment]
Same error with kernel 5.18-rc2. Build without issues with kernel 5.17.2

**Comment by chinh4thepro** [comment]
> Same error with kernel 5.18-rc2. Build without issues with kernel 5.17.2

how did you manage to do that?

**Comment by BenjaminWegener** [comment]
i think @danijell2 used the libre kernel in ./config,
trying it now too

**Comment by chinh4thepro** [comment]
seems like debian builds fine with the libre kernel

**Comment by Maccraft123** [comment]
fixed in https://github.com/Maccraft123/Cadmium/commit/2767a4b3bb319c3751ecb56611168cc6201d2d09
