### ISSUE TITLE
error retreiving file (ARCH BUILD)

### ISSUE THREAD

**Issue by BenjaminWegener** [Maccraft123/Cadmium#125]
i get an error tryong to build arch iso. maybe an mirror is down?

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 linux-aarch64-5.17.1-1-aarch64.pkg.tar.xz failed to download
 Total ( 1/87)         193.1 MiB  18.1 MiB/s 00:11 [######################] 100%
error: failed retrieving file 'linux-aarch64-5.17.1-1-aarch64.pkg.tar.xz' from mirror.archlinuxarm.org : Connection timeout after 10001 ms
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

https://archlinux.pkgs.org/rolling/archlinux-core-aarch64/linux-aarch64-5.17.1-1-aarch64.pkg.tar.xz.html is working, could be exchanged AFAIK

**Comment by Maccraft123** [comment]
that's an issue with your internet

**Comment by BenjaminWegener** [comment]
works now again, had no internet problems, maybe arch server issue. nevermind, thanks @Maccraft123
