### ISSUE TITLE
file not found (UBUNTU BUILD)

### ISSUE THREAD

**Issue by BenjaminWegener** [Maccraft123/Cadmium#126]
got this error on ubuntu impish
++ uname -m
+ '[' aarch64 = aarch64 ']'
+ echo 'Running natively, not using qemu'
Running natively, not using qemu
+ /home/linux/Documents/Cadmium-FENNEL14/fs/ubuntu/build /home/linux/Documents/Cadmium-FENNEL14/tmp/root
/home/linux/Documents/Cadmium-FENNEL14/fs/build: line 37: /home/linux/Documents/Cadmium-FENNEL14/fs/ubuntu/build: No such file or directory

**Comment by chinh4thepro** [comment]
i believe ubuntu isn't supported right now

**Comment by BenjaminWegener** [comment]
dunno, would have been nice to mention it
