### ISSUE TITLE
Building arch fails

### ISSUE THREAD

**Issue by chinh4thepro** [Maccraft123/Cadmium#132]
I'm trying to build arch and I get.

> arch-chroot /home/chinh4thepro/cadmium/tmp/root /usr/bin/pacman-key --init
> chroot: failed to run command ‘/usr/bin/pacman-key’: Exec format error

This might have to be due to me using arch to build it

**Comment by Maccraft123** [comment]
you need binfmt configured to use qemu-user-static

niedz., 8 maj 2022, 23:52 użytkownik chinh4thepro ***@***.***>
napisał:

**Comment by chinh4thepro** [comment]
Thanks it works now, I thought I had it already installed
