### ISSUE TITLE
building to usb: 2 of 12 hunks failed

### ISSUE THREAD

**Issue by linreigu** [Maccraft123/Cadmium#172]
Building to usb, I get

Hunk #1 succeeded at 81 (offset 1 line).
Hunk #2 FAILED at 94.
Hunk #3 FAILED at 242.
Hunk #4 succeeded at 299 (offset 25 lines).
Hunk #5 succeeded at 387 (offset 25 lines).
Hunk #6 succeeded at 488 (offset 25 lines).
Hunk #7 succeeded at 504 (offset 25 lines).
Hunk #8 succeeded at 523 (offset 25 lines).
Hunk #9 succeeded at 540 (offset 25 lines).
Hunk #10 succeeded at 552 (offset 25 lines).
Hunk #11 succeeded at 684 (offset 28 lines).
Hunk #12 succeeded at 700 with fuzz 2 (offset 28 lines).
2 out of 12 hunks FAILED -- saving rejects to file drivers/gpu/drm/rockchip/dw_hdmi-rockchip.c.rej

How to proceed?

Erik

**Comment by CZemft** [comment]
I'm getting the same error when building to file

**Comment by Maccraft123** [comment]
Fixed
