### ISSUE TITLE
Can you try to boot windows 11 on duet

### ISSUE THREAD

**Issue by zainullahk** [Maccraft123/Cadmium#21]
I know it would be a lot of work but it has been working on rasberry pi and Lumia and OnePlus 6t you can get the insider iso via uudump

**Comment by zainullahk** [comment]
Also when downloading the iso make sure to disable the 3gb ram limit with rpi uefi

**Comment by Maccraft123** [comment]
there is literally no point in doing that even if it's possible.

**Comment by zainullahk** [comment]
Why

**Comment by LoganMD** [comment]
LOL
