### ISSUE TITLE
No bluetooth on 5.14rc1 on debian sid

### ISSUE THREAD

**Issue by michaelAschmid** [Maccraft123/Cadmium#30]
dmesg output: 
`[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Reading QCA version information failed (-110)
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Retry BT power ON:1
[Mi Jul 14 17:55:59 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA Product ID   :0x00000008
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA SOC Version  :0x00000044
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA ROM Version  :0x00000302
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA Patch Version:0x00000111
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA controller version 0x00440302
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA Downloading qca/rampatch_00440302.bin
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: Frame reassembly failed (-84)
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA Downloading qca/nvm_00440302_i2s_eu.bin
[Mi Jul 14 17:56:00 2021] Bluetooth: hci0: QCA setup on UART is completed
[Mi Jul 14 17:56:00 2021] debugfs: Directory 'ibs' with parent 'hci0' already present!
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: mem_dump_status: 3
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: clearing allocated memory due to memdump timeout
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: setting up ROME/QCA6390
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA Product ID   :0x00000008
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA SOC Version  :0x00000044
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA ROM Version  :0x00000302
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA Patch Version:0x000003e8
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA controller version 0x00440302
[Mi Jul 14 17:56:01 2021] Bluetooth: hci0: QCA Downloading qca/rampatch_00440302.bin
[Mi Jul 14 17:56:03 2021] Bluetooth: hci0: command 0xfc00 tx timeout
[Mi Jul 14 17:56:03 2021] Bluetooth: hci0: crash the soc to collect controller dump
`

but bluethooth.service seems to be running and also drops a few error into the journal:

`Jul 14 17:29:16 kukui bluetoothd[433]: Bluetooth daemon 5.55
Jul 14 17:29:16 kukui systemd[1]: Starting Bluetooth service...
Jul 14 17:29:16 kukui bluetoothd[433]: Starting SDP server
Jul 14 17:29:16 kukui bluetoothd[433]: Bluetooth management interface 1.21 initialized
Jul 14 17:29:16 kukui systemd[1]: Started Bluetooth service.
Jul 14 17:29:16 kukui bluetoothd[433]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Jul 14 17:29:16 kukui bluetoothd[433]: sap-server: Operation not permitted (1)
Jul 14 17:29:17 kukui bluetoothd[433]: Endpoint registered: sender=:1.28 path=/MediaEndpoint/A2DPSink/sbc
Jul 14 17:29:17 kukui bluetoothd[433]: Endpoint registered: sender=:1.28 path=/MediaEndpoint/A2DPSource/sbc
Jul 14 17:29:37 kukui bluetoothd[433]: Endpoint registered: sender=:1.62 path=/MediaEndpoint/A2DPSink/sbc
Jul 14 17:29:37 kukui bluetoothd[433]: Endpoint registered: sender=:1.62 path=/MediaEndpoint/A2DPSource/sbc
Jul 14 17:29:37 kukui bluetoothd[433]: src/profile.c:ext_start_servers() RFCOMM server failed for Headset Voice gateway: rfcomm_bind>
Jul 14 17:29:37 kukui bluetoothd[433]: src/profile.c:ext_start_servers() RFCOMM server failed for Headset unit: rfcomm_bind: Address>
Jul 14 17:29:44 kukui bluetoothd[433]: Endpoint unregistered: sender=:1.28 path=/MediaEndpoint/A2DPSink/sbc
Jul 14 17:29:44 kukui bluetoothd[433]: Endpoint unregistered: sender=:1.28 path=/MediaEndpoint/A2DPSource/sbc
Jul 14 17:48:00 kukui bluetoothd[433]: Terminating
Jul 14 17:48:00 kukui systemd[1]: Stopping Bluetooth service...
Jul 14 17:48:00 kukui bluetoothd[433]: Endpoint unregistered: sender=:1.62 path=/MediaEndpoint/A2DPSink/sbc
Jul 14 17:48:00 kukui bluetoothd[433]: Endpoint unregistered: sender=:1.62 path=/MediaEndpoint/A2DPSource/sbc
Jul 14 17:48:00 kukui bluetoothd[433]: Stopping SDP server
Jul 14 17:48:00 kukui bluetoothd[433]: Exit
Jul 14 17:48:00 kukui systemd[1]: bluetooth.service: Succeeded.
Jul 14 17:48:00 kukui systemd[1]: Stopped Bluetooth service.
Jul 14 17:48:00 kukui systemd[1]: Starting Bluetooth service...
Jul 14 17:48:00 kukui bluetoothd[3100]: Bluetooth daemon 5.55
Jul 14 17:48:00 kukui systemd[1]: Started Bluetooth service.
Jul 14 17:48:00 kukui bluetoothd[3100]: Starting SDP server
Jul 14 17:48:00 kukui bluetoothd[3100]: Bluetooth management interface 1.21 initialized
Jul 14 17:48:00 kukui bluetoothd[3100]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Jul 14 17:48:00 kukui bluetoothd[3100]: sap-server: Operation not permitted (1)
Jul 14 17:48:00 kukui bluetoothd[3100]: Endpoint registered: sender=:1.62 path=/MediaEndpoint/A2DPSink/sbc
Jul 14 17:48:00 kukui bluetoothd[3100]: Endpoint registered: sender=:1.62 path=/MediaEndpoint/A2DPSource/sbc
Jul 14 17:48:02 kukui bluetoothd[3100]: Loading LTKs timed out for hci0
`

**Comment by michaelAschmid** [comment]
I would like to reopen the issue, because there was no real fix provided. And marking in the readme that bluetooth does not work, is not a mature way to solving that issue, because it still exists. Cheers

**Comment by ericcurtin** [comment]
Marked as fixed again here, what fixed this?

https://github.com/Maccraft123/Cadmium/commit/d0250587930201a37a90b7b28a7146b9a4ca77d7
