### ISSUE TITLE
rust and java segfault due to missing CONFIG_KUSER_HELPERS

### ISSUE THREAD

**Issue by undrwater** [Maccraft123/Cadmium#35]
Per title. If one attempts to use java or rust (cargo), it will segfault. In dmesg the output is:

`[ 5836.191068] cargo: CONFIG_KUSER_HELPERS disabled at 0xffff0fe0`
`[ 5962.962638] java: CONFIG_KUSER_HELPERS disabled at 0xffff0ffc`

**Comment by AsessionGuy** [comment]
It should be working now as CONFIG_KUSER_HELPERS is set to y in both arm and arm64
(I also run cargo with no problems)
