### ISSUE TITLE
Cadmium build fails on mmcblk devices

### ISSUE THREAD

**Issue by apple-corps** [Maccraft123/Cadmium#37]
As mentioned via discord, the Cadmium build fails on mmcblk devices. A possible fix #33 is setting the partition values for the shell script after partitioning. Opening an issue in case another user is having build troubles.

https://github.com/Maccraft123/Cadmium/pull/33

**Comment by Wooty-B** [comment]
Is this still occurring? I have had no issue installing Cadmium via uSD nor internal eMMC (both block devices) using the install scripts on an Asus C201 Veyron.

**Comment by Maccraft123** [comment]
Fixed
