### ISSUE TITLE
fixed usb patch and working xorg on duet

### ISSUE THREAD

**Issue by hexdump0815** [Maccraft123/Cadmium#4]
just to keep you up to date: i think i got the usb patch working on the latest v5.10.x kernels (tested with usb audio on v5.10.20) - https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/patches/5.10.20/usb.patch

also i got xorg working on the duet using this xorg.conf: https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/misc/krane-xorg.conf - i also removed CONFIG_DRM_VGEM to only have the usual 2 dri devices (display and gpu)

maybe for xorg there are also some other of my config options used required - not sure - maybe have a look at: https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/options/additional-options-special-mod.txt and https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/options/additional-options-special-yes.txt

good luck and best wishes - hexdump

**Comment by Maccraft123** [comment]
Thank you! How is performance of Xorg on duet?

**Comment by hexdump0815** [comment]
i did not do any benchmarking, but it seems to be useable ... software cursor seems to be required, otherwise getting to a certain point with the cursor feels more like a computer game :)

**Comment by hexdump0815** [comment]
just checked: glmark2 score is 235 (with xfce) while i think i'm getting around 600 with wayfire, but this relation seems to not be too uncommon - see: https://forum.odroid.com/viewtopic.php?p=318172#p318172

**Comment by Maccraft123** [comment]
>software cursor seems to be required, otherwise getting to a certain point
with the cursor feels more like a computer game :)
Gnome 3 on wayland has the same issue for your information so it may be
gnome-specific and not xorg-specific if you have been testing on gnome
Thank you for making it work!

niedz., 7 mar 2021 o 12:12 hexdump0815 <notifications@github.com>
napisał(a):

**Comment by hexdump0815** [comment]
no i did not test in gnome, but in xfce - just reran it and did pin glmark2 to only the fast cores and got 391 :)
