### ISSUE TITLE
Cannot run Armv7 user land

### ISSUE THREAD

**Issue by colemancda** [Maccraft123/Cadmium#41]
Its been impossible to run either a Armv7 chroot (Bullseye armhf) or get multi arch working in Debian.

**Comment by WizzardSK** [comment]
We just need to set CONFIG_COMPAT=y in kernel config file and it will work

**Comment by colemancda** [comment]
The problem is that it seems to already enabled. 
https://github.com/Maccraft123/Cadmium/blob/fa333f5c6c7ab84721fdce97cf77d8fca1fe3e13/baseboard/gru/kernel-config#L409

**Comment by colemancda** [comment]
So, it seems the files available for download don't match, I just extracted the config from my running system on gru_kevin (Samsung Chromebook Plus v1) and its not set.

**Comment by WizzardSK** [comment]
When did you install your Cadmium? Cause it is set just in the latest commit that breaks the kernel.

**Comment by colemancda** [comment]
I installed yesterday with the latest release. Gonna try to build.

**Comment by WizzardSK** [comment]
That is very strange because I was not able to boot it. Did you use the release or master branch? I think that tagged release is older and does not contain the latest changes.

**Comment by colemancda** [comment]
Correct, it's older.

**Comment by colemancda** [comment]
Built from source and tested on Kevin. Multiarch and armhf chroot work now.
