### ISSUE TITLE
Please add MT8183C support 

### ISSUE THREAD

**Issue by krome-3k** [Maccraft123/Cadmium#57]
Hi,
Can you please add support for the MT8183C SoC? Its used in a few recent chromebooks like mine (Acer Spin 311). Is it possible to build from source in ubuntu chroot on my device for my device?
Thanks in advance.

**Comment by chinh4thepro** [comment]
nvm

**Comment by krome-3k** [comment]
Can you please guide me? I want to build it from source on my device.

**Comment by chinh4thepro** [comment]
on your chromebook?

**Comment by chinh4thepro** [comment]
im still having problems with how to build it 😭

**Comment by krome-3k** [comment]
> on your chromebook?
> 

Yes

**Comment by krome-3k** [comment]
> im still having problems with how to build it 😭

Oh.. okay

**Comment by krome-3k** [comment]
@Maccraft123 : Can you please help us?

**Comment by chinh4thepro** [comment]
also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu

**Comment by chinh4thepro** [comment]
there is support for the soc you want to run it on

**Comment by chinh4thepro** [comment]
but im not sure if it supports the hardware and the code name isn't the same

**Comment by krome-3k** [comment]
> also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu

I installed ubuntu chroot using crouton but only xenial is stable. Will that do?

**Comment by chinh4thepro** [comment]
> > also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu
> 
> I installed ubuntu chroot using crouton but only xenial is stable. Will that do?

yea I think that might work

**Comment by krome-3k** [comment]
> but im not sure if it supports the hardware and the code name isn't the same 

My device is juniper. I am sure i have to build it from source. Can AMD64 build programs for ARM64? I only have this device and raspberry pi4 with ARM64 processors.

**Comment by krome-3k** [comment]
> there is support for the soc you want to run it on

Thats good!

**Comment by chinh4thepro** [comment]
> > there is support for the soc you want to run it on
> 
> Thats good!

I'm not sure about the baseboard tho

**Comment by krome-3k** [comment]
> > > there is support for the soc you want to run it on
> > 
> > Thats good!
> 
> I'm not sure about the baseboard tho

Isnt it always better to build from source?

**Comment by chinh4thepro** [comment]
i think they might have to add your baseboard

**Comment by chinh4thepro** [comment]
because yours is grunt while the one they have supported is kukui

**Comment by krome-3k** [comment]
> because yours is grunt while the one they have supported is kukui

Where did you that? Please share the link.

**Comment by michaelAschmid** [comment]
> also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu

you can do it on whatever distro you want.

**Comment by michaelAschmid** [comment]
> > but im not sure if it supports the hardware and the code name isn't the same
> 
> My device is juniper. I am sure i have to build it from source. Can AMD64 build programs for ARM64? I only have this device and raspberry pi4 with ARM64 processors and one i7 X64.

Ever heard of cross compilation?

**Comment by krome-3k** [comment]
> > > but im not sure if it supports the hardware and the code name isn't the same
> > 
> > My device is juniper. I am sure i have to build it from source. Can AMD64 build programs for ARM64? I only have this device and raspberry pi4 with ARM64 processors and one i7 X64.
> 
> Ever heard of cross compilation?

Yes, but I am a newbie coder, I have zero knowledge. Can you please teach me?

**Comment by michaelAschmid** [comment]
https://wiki.debian.org/CrossCompiling read this guide first.

**Comment by krome-3k** [comment]
> > > also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu
> > 
> > I installed ubuntu chroot using crouton but only xenial is stable. Will that do?
> 
> yea I think that might work

Please guide me further.

**Comment by michaelAschmid** [comment]
> > > > also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu
> > > 
> > > 
> > > I installed ubuntu chroot using crouton but only xenial is stable. Will that do?
> > 
> > 
> > yea I think that might work
> 
> Please guide me further.

I am fairly certain that this wont work.

**Comment by krome-3k** [comment]
> https://wiki.debian.org/CrossCompiling read this guide first.

Thanks, can i dm you if i have any doubts?

**Comment by michaelAschmid** [comment]
> > https://wiki.debian.org/CrossCompiling read this guide first.
> 
> Thanks, can i dm you if i have any doubts?

yes

**Comment by krome-3k** [comment]
> > > https://wiki.debian.org/CrossCompiling read this guide first.
> > 
> > Thanks, can i dm you if i have any doubts?
> 
> yes

I have only used crouton before, how to i manually build a chroot? Is it as simple as extracting a rootfs?

**Comment by krome-3k** [comment]
> > > > > also you can't do it on your Chromebook you need a Linux machine preferably debian or ubuntu
> > > > 
> > > > 
> > > > I installed ubuntu chroot using crouton but only xenial is stable. Will that do?
> > > 
> > > 
> > > yea I think that might work
> > 
> > Please guide me further.
> 
> I am fairly certain that this wont work.

Okay, thanks.

**Comment by chinh4thepro** [comment]
> > because yours is grunt while the one they have supported is kukui
> 
> Where did see you that? Please share the link.

https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices

**Comment by chinh4thepro** [comment]
its accually jaccuzi

**Comment by chinh4thepro** [comment]
![image](https://user-images.githubusercontent.com/34662114/131535854-660923c8-7650-49d1-8b35-fcacd9a5d956.png)

**Comment by chinh4thepro** [comment]
![image](https://user-images.githubusercontent.com/34662114/131535916-2eb56004-6ff6-4e5d-bad6-b8928c09fb87.png)

**Comment by michaelAschmid** [comment]
@chinh4thepro dont spam the issue use the discord server or IRC CHANNEL

**Comment by chinh4thepro** [comment]
ok

**Comment by krome-3k** [comment]
@michaelAschmid : How do i add support for my hardware?

**Comment by chinh4thepro** [comment]
> @michaelAschmid : How do i add support for my hardware?

ask devs😭

**Comment by krome-3k** [comment]
> > @michaelAschmid : How do i add support for my hardware?
> 
> ask devs😭
> 

Thats why i didnt ask you.

**Comment by michaelAschmid** [comment]
@chinh4thepro dont spam the issue use the discord server or IRC CHANNEL

> @michaelAschmid : How do i add support for my hardware?

you need to port your device. but lets discuss this on discord. not here in the issue

**Comment by krome-3k** [comment]
Okay

**Comment by chinh4thepro** [comment]
lol

**Comment by Maccraft123** [comment]
umm.... this is literally same chip as mt8183.

**Comment by colemancda** [comment]
You probably just need to modify the kernel.its to include your dts.

**Comment by krome-3k** [comment]
> umm.... this is literally same chip as mt8183.

Yes, 8183c is for chromebooks and 8183 is for tablets

**Comment by krome-3k** [comment]
> You probably just need to modify the kernel.its to include your dts. 

Please tell me how to do that.
