### ISSUE TITLE
striped screen when booting from USB on Duet - Cadmium v0.4.0-pre1

### ISSUE THREAD

**Issue by ubgen** [Maccraft123/Cadmium#70]
Hello,

I just downloaded the updated Cadmium release for Duet (v0.4.0-pre1), but while booting from USB, screen is all black or horizontally striped (black and white). Not working at all.

**Comment by pojntfx** [comment]
@ubgen I set up automated weekly builds of the latest `master` branch here: https://github.com/pojntfx/cadmium-builds - the latest build for the `duet` is working fine now :)

**Comment by xBl4ckB1rd** [comment]
Your are a hero! @pojntfx  

I am actively diving into this project to develop a pen testing suite for arm based devices. I will try one of your automated builds.

**Comment by Maccraft123** [comment]
Should be fixed in latest pre release. Closing
