### ISSUE TITLE
Build fails due to drm_sched_job_add_implicit_dependencies_fix_harder.patch

### ISSUE THREAD

**Issue by ryjelsum** [Maccraft123/Cadmium#74]
Hello, great project, absolutely love it that you're helping provide these devices some love. Wish I came across it earlier :) 

I tried to build an image for my 'kevin' using the git repository as of commit 5daf7d2d1fceda5d14a87572b0cff2bd9fe97100 , which failed with this error message: 

```
Applying /home/jrg/Cadmium/kernel/patches/drm_sched_job_add_implicit_dependencies_fix_harder.patch
patching file drivers/gpu/drm/scheduler/sched_main.c
Hunk #1 FAILED at 704.
1 out of 1 hunk FAILED -- saving rejects to file drivers/gpu/drm/scheduler/sched_main.c.rej
```

It seems that this 'drm_sched_job_add_implicit_dependencies_fix_harder.patch' patch file was added to fix issues with one specific platform, but it causes the build to fail for others. (My speculation based on the commit adding it, I could be totally wrong.)

Removing this newly added patch file allows the build to continue normally. I unfortunately am way out of my element here and cannot suggest a fix that retains the intended purpose of this patch.

**Comment by Maccraft123** [comment]
Fixed by: https://github.com/Maccraft123/Cadmium/commit/c900aabaddfa5ecb46fd3bc5f5e3555f34d90998#diff-755467882c086f6a61b9bd9ffa6b4ca47a66b207f9326cfcbd90cac69e3a8828
