### ISSUE TITLE
Kernel build fails for speedy

### ISSUE THREAD

**Issue by peter-marshall5** [Maccraft123/Cadmium#75]
Building Cadmium for Veyron Speedy fails with the following error:
cp: cannot stat '/home/peter/Cadmium/kernel/config.arm': No such file or directory

Changing line 41 of kernel/build to "[ -f .config ] || cp $CADMIUMROOT/baseboard/veyron/kernel-config .config" tempoarily fixes the issue.

**Comment by Maccraft123** [comment]
Fixed-by: https://github.com/Maccraft123/Cadmium/commit/37986c7a0ee80fce827ad7084d6fbd1c08af52a5
