### ISSUE TITLE
noob issue: success building for duet, but what is the login user and password?

### ISSUE THREAD

**Issue by dji-transpire** [Maccraft123/Cadmium#83]
I built the installer successfully on an ARM Linux laptop (pinebook pro) and am now faced with unknown loginb username and password when booting the USB image on the Duet.

**Comment by eqixcx** [comment]
Hey! all good, login as root and it should just login straight away :)

**Comment by dji-transpire** [comment]
Hi thanks for this, but unfortunately this would be too easy :-(
Login without password or root/root does not work. 
I probably need to chroot on the pine book and set a password for the root account.
Sent from Yahoo Mail on Android 
 
  On Sat, Dec 18, 2021 at 8:48 AM, Cooper ***@***.***> wrote:   


Hey! all good, login as root and it should just login straight away :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by eqixcx** [comment]
Ah okay, the master branch might be broken at the moment, @Maccraft123 rvstry mentioned an issue in master would this be something to do with it?

**Comment by dji-transpire** [comment]
Ok, thanks for letting me know.  I will try to go the chroot route and see whether I can change the root password.

Sent from Yahoo Mail on Android 
 
  On Sat, Dec 18, 2021 at 10:33 AM, Cooper ***@***.***> wrote:   


Ah okay, the master branch might be broken at the moment, @Maccraft123 rvstry mentioned an issue in master would this be something to do with it?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Maccraft123** [comment]
Due to filesystem rewrite root password ATM isn't being reseted, tomorrow
will fix though

**Comment by Maccraft123** [comment]
Closed-by: https://github.com/Maccraft123/Cadmium/commit/63e08f12eab3ffdb81ebc624c9a4b8dc3eb05bba
