### ISSUE TITLE
Duet 5 image not valid

### ISSUE THREAD

**Issue by j-mir-prazak** [Maccraft123/Cadmium#90]
Trying to build image from master v0.4.0-pre1 for lenovo Duet 5: TARGET=krane, but if i try to boot, it just beeps loadly and says "no valid image found".

i am running latest stable update, dev_mode enabled.

i am not sure if krane is only duet or even duet 5 either - maybe could be better documented in the tables?

thanks

**Comment by Maccraft123** [comment]
Set TARGET to "homestar" in config.
krane is for Lenovo Chromebook Duet with MT8183 SoC

**Comment by Maccraft123** [comment]
And also Homestar is only supported in `master` branch.

**Comment by j-mir-prazak** [comment]
@Maccraft123 thanks!
i did run the script: ubuntu hirsute spills error at the end:

<details>
<summary>bash output</summary>
+ . /home/kabina/compile/Cadmium/config

++ '[' '' = '' ']'

++ TARGET=homestar

++ ROOTFS=ubuntu

++ FILESYSTEM=ext4

++ SUITE=hirsute

++ KERNEL=kernelorg

++ IN_RAM=false

+ . /home/kabina/compile/Cadmium/board/homestar/boardinfo

++ export BASEBOARD=trogdor

++ BASEBOARD=trogdor

++ export BOARD=homestar

++ BOARD=homestar

++ export TYPE=convertible-tablet

++ TYPE=convertible-tablet

++ export WLR_DISP=eDP-1

++ WLR_DISP=eDP-1

++ export DISP_ROTATION=0

++ DISP_ROTATION=0

+ . /home/kabina/compile/Cadmium/baseboard/trogdor/boardinfo

++ export ARCH=arm64

++ ARCH=arm64

++ export ARCH_UNAME=aarch64

++ ARCH_UNAME=aarch64

++ export ARCH_DEB=arm64

++ ARCH_DEB=arm64

++ export CROSS_COMPILE=aarch64-linux-gnu-

++ CROSS_COMPILE=aarch64-linux-gnu-

++ export EMMC_OFFSET=0

++ EMMC_OFFSET=0

++ export SOC=sc7180

++ SOC=sc7180

++ export BOOTFW=depthcharge

++ BOOTFW=depthcharge

++ uname -m

+ '[' x86_64 = aarch64 ']'

+ case "$ARCH_UNAME" in

++ which qemu-aarch64-static

+ cp /usr/bin/qemu-aarch64-static /home/kabina/compile/Cadmium/tmp/root/qemu-aarch64-static

+ qemu=/qemu-aarch64-static

+ echo 'Emulating with qemu'

Emulating with qemu

+ /home/kabina/compile/Cadmium/fs/ubuntu/build /home/kabina/compile/Cadmium/tmp/root

/home/kabina/compile/Cadmium/fs/build: line 38: /home/kabina/compile/Cadmium/fs/ubuntu/build: No such file

 or directory              
</details>

script for sid runs okey, but the image is still invalid. will test one more time though...

thanks
j

**Comment by j-mir-prazak** [comment]
ok, managed to create valid image: f2fs, but not sure, if necessary. but the installl script ends on maleformated if statement (though the last statement). 

i was able to install stuff to the flash drive and it was persistent after reboot, however the firmware for wifi is not loaded, so i had gnome but no wifi afterwards. i am sure most of the patches are not applied: install to flash drive also does not work and breaks sooner than install to system memory (there is no mount point for rootfs i think).

howevery i stay corrected and the image boots and the system actually works.

would you want be to get you the line numbers of the errors?

**Comment by Maccraft123** [comment]
>
> i know what's wrong, i just don't have time, nor development setup to fix
it

**Comment by Maccraft123** [comment]
Fixed in one of recent commits
