### ISSUE TITLE
Bob (Asus C101PA) doesn't boot, only beeps at white screen

### ISSUE THREAD

**Issue by cvmiller** [Maccraft123/Cadmium#93]
Downloaded pre-built image for Bob from release 3.0. Ran sha1sum against download, looks good. Burned to a USB drive with Balena-Etcher. Booted Bob, pressed ctrl+U to boot from USB, Chromebook just beeps.

Any suggestions?

**Comment by chinh4thepro** [comment]
have you tried enable_dev_usb_boot?

**Comment by cvmiller** [comment]
Sorry, I should have mentioned that. Yes, I have enabled USB boot, and the Chromebook produces a loud BEEP when I press ctrl+U. Only a ctrl+D allows me to continue booting (into ChromeOS)

**Comment by chinh4thepro** [comment]
You could try building the image yourself and see if it boots.

**Comment by cvmiller** [comment]
Thanks, I don't have a build system setup at the moment. When I get a larger block of time, I"ll give that a try. I also have an Asus C201PA, I'll download the image for that, and give it a try.

**Comment by eqixcx** [comment]
> Sorry, I should have mentioned that. Yes, I have enabled USB boot, and the Chromebook produces a loud BEEP when I press ctrl+U. Only a ctrl+D allows me to continue booting (into ChromeOS)
> 

All the loud beep means is it can't see a valid boot medium from your selection, you can try one of my builds if you want?

**Comment by jackson-57** [comment]
I tried to flash a cadmium image I had built onto a usb stick for the duet using etcher, and it didn't boot either. I used `dd` to flash it onto the usb and that seemed to work for me.

**Comment by cvmiller** [comment]
Just tried the Speedy image on my C201PA, and same "beeping" problem. It doesn't find the USB bootable. Is there a trick other than `dd` or Etcher to get the image onto the USB that I am missing?

**Comment by chinh4thepro** [comment]
have you tried any other usbs?

**Comment by cvmiller** [comment]
I have only tried the latest release USB images, both for C101PA (Bob) and C201PA (Speedy). Neither boot their respective Chromebooks. Which "other" USB images did you have in mind?

**Comment by chinh4thepro** [comment]
there is eqixcx's "automated" builds that you could try

**Comment by cvmiller** [comment]
No I haven't. Thanks for the pointer. Here's the link for those who are following along

https://github.com/eqixcx/cadmium-builds/releases/tag/latest

**Comment by cvmiller** [comment]
Tried "burning" image to a different USB stick (actually a SD card in a SD Card to USB adapter). This boots Speedy (C201PA) both from the USB adapter/SD card, and from the SD Card alone.

It would be nice if eqixcx's builds also included Speedy (C201PA).

**Comment by cvmiller** [comment]
Now that my C201PA boots, I am going to close this issue.
