### ISSUE TITLE
Cadmium installer -script fails on device: "chroot: cannot change root directory to 'apt': No such file or directory"

### ISSUE THREAD

**Issue by askolsam** [Maccraft123/Cadmium#97]
Version: built from master
Device: kukui/krane

Running `/root/install` -script on the device will fail with message `chroot: cannot change root directory to 'apt': No such file or directory`.

`BOOTFW_INST_PKGS` is being set in
https://github.com/Maccraft123/Cadmium/blob/099140ed14f135a5a565b792ee937da78e1def59/fs/install#L74

and the variable is being consumed in 
https://github.com/Maccraft123/Cadmium/blob/099140ed14f135a5a565b792ee937da78e1def59/fs/install#L155

However, `DESTDIR` is still undefined when `BOOTFW_INST_PKGS` is being set, resulting to invalid `chroot` command. 

DESTDIR is set as late as
https://github.com/Maccraft123/Cadmium/blob/099140ed14f135a5a565b792ee937da78e1def59/fs/install#L120

**Comment by madds-h** [comment]
I noticed this was wrong when installing last night, and fixed it in #96 by moving DESTDIR up before the BOOTFW_INST_PKGS.
